#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
    name: product-data-service  #设置微服务的名称： product-data-service
  zipkin:
    base-url: http://localhost:9411   #通过 zipkin 服务链路追踪服务器
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    #设置注册中心的地址： http://localhost:8761/eureka/, 与eureka-server 中的配置 application.yml 遥相呼应
